---
- name: Install latest version of httpd
  ansible.builtin.dnf:
    name: httpd
    state: latest
    update_cache: true
- name: Update template and copy to destination server
  ansible.builtin.template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: true
- name: Create base directory
  ansible.builtin.file:
    path: '/var/www/{{ httpd_host_fqdn }}'
    state: directory
    mode: '0755'
- name: Create http directory
  ansible.builtin.file:
    path: '/var/www/{{ httpd_host_fqdn }}/public_html'
    state: directory
    mode: '0755'
- name: Restart and enable httpd daemon
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: true
